"""Add is_right field for answer

Revision ID: 0eec43c63af9
Revises: 85df056f947b
Create Date: 2019-06-06 15:46:42.070464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eec43c63af9'
down_revision = '85df056f947b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('is_right', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'is_right')
    # ### end Alembic commands ###
