"""Channel id column for tests

Revision ID: 21c3af5c570e
Revises: b3c2abd46e20
Create Date: 2019-06-07 20:27:05.790335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c3af5c570e'
down_revision = 'b3c2abd46e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('channel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'channel_id')
    # ### end Alembic commands ###
