"""Add quizzes table

Revision ID: 904663e9af64
Revises: 514d4b4d45f0
Create Date: 2019-05-30 16:04:41.211090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '904663e9af64'
down_revision = '514d4b4d45f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('top_count', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('test', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.drop_constraint('test_ibfk_1', 'test', type_='foreignkey')
    op.create_foreign_key(None, 'test', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('test', 'answer_id')
    op.drop_column('test', 'channel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('channel_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('answer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.create_foreign_key('test_ibfk_1', 'test', 'channel', ['channel_id'], ['id'])
    op.drop_column('test', 'quiz_id')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
