"""quiz_id column for answer

Revision ID: b3c2abd46e20
Revises: c2aac9f8cb13
Create Date: 2019-06-07 20:04:19.014159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c2abd46e20'
down_revision = 'c2aac9f8cb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('quiz_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'quiz_id')
    # ### end Alembic commands ###
