"""Publish date for tests

Revision ID: de14a0441ce0
Revises: 904663e9af64
Create Date: 2019-05-31 19:29:18.814790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de14a0441ce0'
down_revision = '904663e9af64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('publish_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'publish_date')
    # ### end Alembic commands ###
